# Generated by Django 5.1.6 on 2025-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbinstances',
            name='access_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
