# Generated by Django 5.1.6 on 2025-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0002_bbinstances_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbinstances',
            name='exposed_path',
            field=models.TextField(default='C:/default/path'),
        ),
        migrations.AddField(
            model_name='bbinstances',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='bbinstances',
            name='port',
            field=models.IntegerField(default=8001),
        ),
    ]
