# Generated by Django 5.1.6 on 2025-06-02 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0003_bbinstances_exposed_path_bbinstances_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbinstances',
            name='accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
